services:
  oracle:
    image: oracle/database:21.3.0-xe
    container_name: oracle-21-build
    shm_size: "2g"         # /dev/shm ≥ 1 Go sinon SGA échoue :contentReference[oaicite:2]{index=2}
    cpus: "4"              # limite à 4 cœurs → SGA mini = 1600M :contentReference[oaicite:3]{index=3}    
    restart: unless-stopped
    ports:
      - "1521:1521"   # SQL*Net
      - "5500:5500"   # EM Express
    environment:
      ORACLE_SID: XE            # valeur fixe pour XE
      ORACLE_PDB: XEPDB1        # nom du PDB créé
      ORACLE_PWD: 'Str0ngPASSWD123' # mot de passe admin attention pas de characters speciaux
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - dbnet              

networks:
  dbnet:
    external: true

volumes:
  oracle-data:
